name: financas_pessoais
description: A new Flutter project.

version: 1.1.10+13

environment:
  sdk: '>=2.11.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  intl: ^0.17.0
  sqflite: ^1.3.2+3
  brasil_fields: ^1.0.0-nullsafety.1
  fl_chart: ^0.12.2
  http: ^0.12.2
  provider: ^4.3.3
  font_awesome_flutter: ^8.11.0
  downloads_path_provider: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icone.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/waiting.png
    - assets/images/icone.png
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/static/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand/static/Quicksand-Bold.ttf
          weight: 700

