name: financas_pessoais
description: A new Flutter project.

version: 1.0.3+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  intl: ^0.16.1
  sqflite: ^1.3.2+3
  brasil_fields: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icone.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/waiting.png
    - assets/images/icone.png
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/static/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand/static/Quicksand-Bold.ttf
          weight: 700

