name: financas_pessoais
description: A new Flutter project.

version: 1.1.3+16

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  sqflite: ^2.0.0+3
  brasil_fields: ^1.1.2
  fl_chart: ^0.35.0
  http: ^0.13.1
  provider: ^5.0.0
  font_awesome_flutter: ^9.0.0
  flutter_charts: ^0.2.0
  curved_navigation_bar: ^0.4.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icone.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/waiting.png
    - assets/images/icone.png
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/static/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand/static/Quicksand-Bold.ttf
          weight: 700

